#pragma once
// The shared DirectX core's guest ABI (re2dj/directx/abi.h) checked against the
// Windows SDK, and the copies between the two. Include after <ddraw.h> and
// <d3d.h>; the Direct3D 7 checks apply when DIRECT3D_VERSION is 0x0700.

#include <cstddef>
#include <cstring>
#include <type_traits>

#include "re2dj/directx/abi.h"

namespace re2dj::platform::windows
{

#define RE2DJ_DIRECTX_SAME_LAYOUT(sdk, core) \
    static_assert(sizeof(sdk) == sizeof(re2dj::directx::core), #sdk " size differs from the core")
#define RE2DJ_DIRECTX_SAME_OFFSET(sdk, sdk_member, core, core_member)                    \
    static_assert(offsetof(sdk, sdk_member) == offsetof(re2dj::directx::core, core_member), \
                  #sdk "." #sdk_member " offset differs from the core")
#define RE2DJ_DIRECTX_SAME_VALUE(sdk, core) \
    static_assert(static_cast<std::uint32_t>(sdk) == re2dj::directx::core, #sdk " differs from the core")

RE2DJ_DIRECTX_SAME_LAYOUT(GUID, Guid);
RE2DJ_DIRECTX_SAME_LAYOUT(DDPIXELFORMAT, DdPixelFormat);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwRGBBitCount, DdPixelFormat, bit_count);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwZBufferBitDepth, DdPixelFormat, bit_count);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwRBitMask, DdPixelFormat, red_mask);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwGBitMask, DdPixelFormat, green_mask);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwZBitMask, DdPixelFormat, green_mask);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwBBitMask, DdPixelFormat, blue_mask);
RE2DJ_DIRECTX_SAME_OFFSET(DDPIXELFORMAT, dwRGBAlphaBitMask, DdPixelFormat, alpha_mask);
RE2DJ_DIRECTX_SAME_LAYOUT(DDSCAPS2, DdsCaps2);
RE2DJ_DIRECTX_SAME_LAYOUT(DDSURFACEDESC2, DdSurfaceDesc2);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, lPitch, DdSurfaceDesc2, pitch);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, dwBackBufferCount, DdSurfaceDesc2, back_buffer_count);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, dwRefreshRate, DdSurfaceDesc2, refresh_rate);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, lpSurface, DdSurfaceDesc2, surface);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, ddckCKSrcBlt, DdSurfaceDesc2, source_blt_key);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, ddpfPixelFormat, DdSurfaceDesc2, pixel_format);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, ddsCaps, DdSurfaceDesc2, caps);
RE2DJ_DIRECTX_SAME_OFFSET(DDSURFACEDESC2, dwTextureStage, DdSurfaceDesc2, texture_stage);
RE2DJ_DIRECTX_SAME_LAYOUT(DDCAPS, DdCaps);
RE2DJ_DIRECTX_SAME_OFFSET(DDCAPS, dwCaps, DdCaps, caps);
RE2DJ_DIRECTX_SAME_OFFSET(DDCAPS, dwCaps2, DdCaps, caps2);
RE2DJ_DIRECTX_SAME_OFFSET(DDCAPS, ddsCaps, DdCaps, surface_caps);
#if DIRECT3D_VERSION >= 0x0700
RE2DJ_DIRECTX_SAME_LAYOUT(D3DPRIMCAPS, D3dPrimCaps);
RE2DJ_DIRECTX_SAME_OFFSET(D3DPRIMCAPS, dwTextureAddressCaps, D3dPrimCaps, texture_address_caps);
RE2DJ_DIRECTX_SAME_LAYOUT(D3DDEVICEDESC7, D3dDeviceDesc7);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, dpcTriCaps, D3dDeviceDesc7, triangle_caps);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, dvGuardBandLeft, D3dDeviceDesc7, guard_band_left);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, wMaxTextureBlendStages, D3dDeviceDesc7, max_texture_blend_stages);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, dwMaxActiveLights, D3dDeviceDesc7, max_active_lights);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, deviceGUID, D3dDeviceDesc7, device_guid);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, wMaxUserClipPlanes, D3dDeviceDesc7, max_user_clip_planes);
RE2DJ_DIRECTX_SAME_OFFSET(D3DDEVICEDESC7, dwVertexProcessingCaps, D3dDeviceDesc7, vertex_processing_caps);
#endif
RE2DJ_DIRECTX_SAME_LAYOUT(DDDEVICEIDENTIFIER2, DdDeviceIdentifier2);
RE2DJ_DIRECTX_SAME_OFFSET(DDDEVICEIDENTIFIER2, liDriverVersion, DdDeviceIdentifier2, driver_version_low);
RE2DJ_DIRECTX_SAME_OFFSET(DDDEVICEIDENTIFIER2, guidDeviceIdentifier, DdDeviceIdentifier2, device_identifier);
RE2DJ_DIRECTX_SAME_OFFSET(DDDEVICEIDENTIFIER2, dwWHQLLevel, DdDeviceIdentifier2, whql_level);

RE2DJ_DIRECTX_SAME_VALUE(DD_OK, kDdOk);
RE2DJ_DIRECTX_SAME_VALUE(DDERR_INVALIDPARAMS, kDdErrInvalidParams);
RE2DJ_DIRECTX_SAME_VALUE(E_NOINTERFACE, kENoInterface);
RE2DJ_DIRECTX_SAME_VALUE(E_POINTER, kEPointer);
RE2DJ_DIRECTX_SAME_VALUE(DDERR_GENERIC, kDdErrGeneric);
RE2DJ_DIRECTX_SAME_VALUE(DDERR_UNSUPPORTEDMODE, kDdErrUnsupportedMode);
RE2DJ_DIRECTX_SAME_VALUE(DDENUMRET_CANCEL, kEnumCancel);
RE2DJ_DIRECTX_SAME_VALUE(DDENUMRET_OK, kEnumContinue);
#if DIRECT3D_VERSION >= 0x0700
RE2DJ_DIRECTX_SAME_VALUE(D3DENUMRET_CANCEL, kEnumCancel);
RE2DJ_DIRECTX_SAME_VALUE(D3DENUMRET_OK, kEnumContinue);
#endif
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS_3D, kDdCaps3d);
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS_BLT, kDdCapsBlt);
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS_COLORKEY, kDdCapsColorKey);
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS2_CERTIFIED, kDdCaps2Certified);
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS2_WIDESURFACES, kDdCaps2WideSurfaces);
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS2_NOPAGELOCKREQUIRED, kDdCaps2NoPageLockRequired);
RE2DJ_DIRECTX_SAME_VALUE(DDCAPS2_CANRENDERWINDOWED, kDdCaps2CanRenderWindowed);
RE2DJ_DIRECTX_SAME_VALUE(DDSCAPS_BACKBUFFER, kDdsCapsBackBuffer);
RE2DJ_DIRECTX_SAME_VALUE(DDSCAPS_PRIMARYSURFACE, kDdsCapsPrimarySurface);
RE2DJ_DIRECTX_SAME_VALUE(DDSCAPS_3DDEVICE, kDdsCaps3dDevice);
RE2DJ_DIRECTX_SAME_VALUE(DDSCAPS_VIDEOMEMORY, kDdsCapsVideoMemory);
RE2DJ_DIRECTX_SAME_VALUE(DDSD_HEIGHT, kDdsdHeight);
RE2DJ_DIRECTX_SAME_VALUE(DDSD_WIDTH, kDdsdWidth);
RE2DJ_DIRECTX_SAME_VALUE(DDSD_PITCH, kDdsdPitch);
RE2DJ_DIRECTX_SAME_VALUE(DDSD_PIXELFORMAT, kDdsdPixelFormat);
RE2DJ_DIRECTX_SAME_VALUE(DDSD_REFRESHRATE, kDdsdRefreshRate);
RE2DJ_DIRECTX_SAME_VALUE(DDPF_ALPHAPIXELS, kDdpfAlphaPixels);
RE2DJ_DIRECTX_SAME_VALUE(DDPF_RGB, kDdpfRgb);
RE2DJ_DIRECTX_SAME_VALUE(DDPF_ZBUFFER, kDdpfZBuffer);
RE2DJ_DIRECTX_SAME_VALUE(DDBD_16, kDdbd16);
RE2DJ_DIRECTX_SAME_VALUE(DDBD_24, kDdbd24);
RE2DJ_DIRECTX_SAME_VALUE(DDBD_32, kDdbd32);
#if DIRECT3D_VERSION >= 0x0700
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_FLOATTLVERTEX, kD3dDevCapsFloatTlVertex);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_EXECUTESYSTEMMEMORY, kD3dDevCapsExecuteSystemMemory);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_TLVERTEXSYSTEMMEMORY, kD3dDevCapsTlVertexSystemMemory);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_TEXTURESYSTEMMEMORY, kD3dDevCapsTextureSystemMemory);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_TEXTUREVIDEOMEMORY, kD3dDevCapsTextureVideoMemory);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_DRAWPRIMTLVERTEX, kD3dDevCapsDrawPrimTlVertex);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_CANRENDERAFTERFLIP, kD3dDevCapsCanRenderAfterFlip);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_DRAWPRIMITIVES2, kD3dDevCapsDrawPrimitives2);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_DRAWPRIMITIVES2EX, kD3dDevCapsDrawPrimitives2Ex);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_HWTRANSFORMANDLIGHT, kD3dDevCapsHwTransformAndLight);
RE2DJ_DIRECTX_SAME_VALUE(D3DDEVCAPS_HWRASTERIZATION, kD3dDevCapsHwRasterization);
RE2DJ_DIRECTX_SAME_VALUE(D3DPMISCCAPS_MASKZ, kD3dPMiscCapsMaskZ);
RE2DJ_DIRECTX_SAME_VALUE(D3DPMISCCAPS_CULLNONE, kD3dPMiscCapsCullNone);
RE2DJ_DIRECTX_SAME_VALUE(D3DPMISCCAPS_CULLCW, kD3dPMiscCapsCullCw);
RE2DJ_DIRECTX_SAME_VALUE(D3DPMISCCAPS_CULLCCW, kD3dPMiscCapsCullCcw);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_DITHER, kD3dPRasterCapsDither);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_ZTEST, kD3dPRasterCapsZTest);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_SUBPIXEL, kD3dPRasterCapsSubPixel);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_FOGVERTEX, kD3dPRasterCapsFogVertex);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_FOGTABLE, kD3dPRasterCapsFogTable);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_ZBIAS, kD3dPRasterCapsZBias);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_WBUFFER, kD3dPRasterCapsWBuffer);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_WFOG, kD3dPRasterCapsWFog);
RE2DJ_DIRECTX_SAME_VALUE(D3DPRASTERCAPS_ZFOG, kD3dPRasterCapsZFog);
RE2DJ_DIRECTX_SAME_VALUE(D3DPCMPCAPS_NEVER | D3DPCMPCAPS_LESS | D3DPCMPCAPS_EQUAL | D3DPCMPCAPS_LESSEQUAL |
                             D3DPCMPCAPS_GREATER | D3DPCMPCAPS_NOTEQUAL | D3DPCMPCAPS_GREATEREQUAL |
                             D3DPCMPCAPS_ALWAYS,
                         kD3dPCmpCapsAll);
RE2DJ_DIRECTX_SAME_VALUE(D3DPBLENDCAPS_ZERO | D3DPBLENDCAPS_ONE | D3DPBLENDCAPS_SRCCOLOR |
                             D3DPBLENDCAPS_INVSRCCOLOR | D3DPBLENDCAPS_SRCALPHA | D3DPBLENDCAPS_INVSRCALPHA |
                             D3DPBLENDCAPS_DESTALPHA | D3DPBLENDCAPS_INVDESTALPHA | D3DPBLENDCAPS_DESTCOLOR |
                             D3DPBLENDCAPS_INVDESTCOLOR | D3DPBLENDCAPS_SRCALPHASAT,
                         kD3dPBlendCapsThroughSrcAlphaSat);
RE2DJ_DIRECTX_SAME_VALUE(D3DPSHADECAPS_COLORGOURAUDRGB, kD3dPShadeCapsColorGouraudRgb);
RE2DJ_DIRECTX_SAME_VALUE(D3DPSHADECAPS_SPECULARGOURAUDRGB, kD3dPShadeCapsSpecularGouraudRgb);
RE2DJ_DIRECTX_SAME_VALUE(D3DPSHADECAPS_ALPHAGOURAUDBLEND, kD3dPShadeCapsAlphaGouraudBlend);
RE2DJ_DIRECTX_SAME_VALUE(D3DPSHADECAPS_FOGGOURAUD, kD3dPShadeCapsFogGouraud);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTEXTURECAPS_PERSPECTIVE, kD3dPTextureCapsPerspective);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTEXTURECAPS_ALPHA, kD3dPTextureCapsAlpha);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTEXTURECAPS_TRANSPARENCY, kD3dPTextureCapsTransparency);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTEXTURECAPS_ALPHAPALETTE, kD3dPTextureCapsAlphaPalette);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_NEAREST, kD3dPTFilterCapsNearest);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_LINEAR, kD3dPTFilterCapsLinear);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MIPNEAREST, kD3dPTFilterCapsMipNearest);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MIPLINEAR, kD3dPTFilterCapsMipLinear);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_LINEARMIPNEAREST, kD3dPTFilterCapsLinearMipNearest);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_LINEARMIPLINEAR, kD3dPTFilterCapsLinearMipLinear);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MINFPOINT, kD3dPTFilterCapsMinFPoint);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MINFLINEAR, kD3dPTFilterCapsMinFLinear);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MIPFPOINT, kD3dPTFilterCapsMipFPoint);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MIPFLINEAR, kD3dPTFilterCapsMipFLinear);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MAGFPOINT, kD3dPTFilterCapsMagFPoint);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTFILTERCAPS_MAGFLINEAR, kD3dPTFilterCapsMagFLinear);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTBLENDCAPS_DECAL, kD3dPTBlendCapsDecal);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTBLENDCAPS_MODULATE, kD3dPTBlendCapsModulate);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTBLENDCAPS_DECALALPHA, kD3dPTBlendCapsDecalAlpha);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTBLENDCAPS_MODULATEALPHA, kD3dPTBlendCapsModulateAlpha);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTBLENDCAPS_COPY, kD3dPTBlendCapsCopy);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTBLENDCAPS_ADD, kD3dPTBlendCapsAdd);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTADDRESSCAPS_WRAP, kD3dPTAddressCapsWrap);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTADDRESSCAPS_MIRROR, kD3dPTAddressCapsMirror);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTADDRESSCAPS_CLAMP, kD3dPTAddressCapsClamp);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTADDRESSCAPS_BORDER, kD3dPTAddressCapsBorder);
RE2DJ_DIRECTX_SAME_VALUE(D3DPTADDRESSCAPS_INDEPENDENTUV, kD3dPTAddressCapsIndependentUv);
RE2DJ_DIRECTX_SAME_VALUE(D3DTEXOPCAPS_DISABLE | D3DTEXOPCAPS_SELECTARG1 | D3DTEXOPCAPS_SELECTARG2 |
                             D3DTEXOPCAPS_MODULATE | D3DTEXOPCAPS_MODULATE2X | D3DTEXOPCAPS_MODULATE4X |
                             D3DTEXOPCAPS_ADD | D3DTEXOPCAPS_ADDSIGNED | D3DTEXOPCAPS_ADDSIGNED2X |
                             D3DTEXOPCAPS_SUBTRACT | D3DTEXOPCAPS_ADDSMOOTH | D3DTEXOPCAPS_BLENDDIFFUSEALPHA |
                             D3DTEXOPCAPS_BLENDTEXTUREALPHA | D3DTEXOPCAPS_BLENDFACTORALPHA |
                             D3DTEXOPCAPS_BLENDTEXTUREALPHAPM | D3DTEXOPCAPS_BLENDCURRENTALPHA,
                         kD3dTexOpCapsThroughBlendCurrentAlpha);
RE2DJ_DIRECTX_SAME_VALUE(D3DVTXPCAPS_TEXGEN, kD3dVtxPCapsTexGen);
RE2DJ_DIRECTX_SAME_VALUE(D3DVTXPCAPS_MATERIALSOURCE7, kD3dVtxPCapsMaterialSource7);
RE2DJ_DIRECTX_SAME_VALUE(D3DVTXPCAPS_VERTEXFOG, kD3dVtxPCapsVertexFog);
RE2DJ_DIRECTX_SAME_VALUE(D3DVTXPCAPS_DIRECTIONALLIGHTS, kD3dVtxPCapsDirectionalLights);
RE2DJ_DIRECTX_SAME_VALUE(D3DVTXPCAPS_POSITIONALLIGHTS, kD3dVtxPCapsPositionalLights);
RE2DJ_DIRECTX_SAME_VALUE(D3DVTXPCAPS_LOCALVIEWER, kD3dVtxPCapsLocalViewer);
#endif

#undef RE2DJ_DIRECTX_SAME_LAYOUT
#undef RE2DJ_DIRECTX_SAME_OFFSET
#undef RE2DJ_DIRECTX_SAME_VALUE

// Copies a core structure over the SDK structure of the same layout.
template <typename Sdk, typename Core>
void CopyFromCore(Sdk* destination, const Core& source)
{
    static_assert(sizeof(Sdk) == sizeof(Core) && std::is_trivially_copyable_v<Core>);
    std::memcpy(destination, &source, sizeof(source));
}

// The SDK GUID of a core identifier.
inline GUID GuidFromCore(const re2dj::directx::Guid& guid)
{
    GUID result;
    std::memcpy(&result, guid.data(), sizeof(result));
    return result;
}

}  // namespace re2dj::platform::windows
