#!/usr/bin/env python3
"""Generates src/hle/unifont_ascii_glyphs.inc from the vendored Unifont hex subset.

Each hex line is "CODE:ROWS", where an 8-pixel-wide glyph has 16 rows of two
hex digits, the leftmost pixel in the high bit. The output is one C++ array
initializer row per character, U+0020 through U+007E in order.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "third_party" / "unifont" / "unifont-15.1.05-ascii.hex"
OUTPUT = ROOT / "src" / "hle" / "unifont_ascii_glyphs.inc"


def main():
    glyphs = {}
    for line in SOURCE.read_text(encoding="ascii").splitlines():
        if not line.strip():
            continue
        code, rows = line.split(":")
        if len(rows) != 32:
            raise SystemExit(f"U+{code} is not an 8x16 glyph")
        glyphs[int(code, 16)] = [int(rows[i:i + 2], 16) for i in range(0, 32, 2)]
    lines = [
        "// Generated by scripts/generate_unifont_glyphs.py from",
        "// third_party/unifont/unifont-15.1.05-ascii.hex (GNU Unifont 15.1.05, SIL OFL 1.1).",
        "// Do not edit: regenerate instead.",
    ]
    for code in range(0x20, 0x7F):
        if code not in glyphs:
            raise SystemExit(f"U+{code:04X} is missing")
        row = ", ".join(f"0x{value:02X}" for value in glyphs[code])
        lines.append(f"{{{row}}},  // U+{code:04X}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")


if __name__ == "__main__":
    main()
