#ifndef RE2DJ_HLE_HARDLOCK_SEED_CONFIG_H_
#define RE2DJ_HLE_HARDLOCK_SEED_CONFIG_H_

#include <filesystem>
#include <optional>
#include <string>
#include <vector>

#include "re2dj/hle/hardlock/engine.h"

namespace re2dj::hle::hardlock
{

// Parses a seed ini file containing [hardlock] section with module_address, seed1, seed2, seed3,
// and optional tail_word.
bool ReadHardlockSeedIni(const std::filesystem::path& path,
                         HardlockSeeds* seeds,
                         std::optional<std::uint16_t>* tail_word,
                         std::string* error);

// Writes a seed ini file with the given seeds and optional tail_word.
bool WriteHardlockSeedIni(const std::filesystem::path& path,
                          const HardlockSeeds& seeds,
                          std::optional<std::uint16_t> tail_word,
                          std::string* error);

// Reads an analysis artifact generated by reSoftlock (hardlock_analysis.json), verifies the
// candidate seeds against the ID_Ref / ID_Verify pair and challenges, and confirms the active seed set.
bool ConfirmSeedsFromAnalysisArtifact(const std::filesystem::path& artifact_path,
                                      HardlockSeeds* confirmed_seeds,
                                      std::string* error);

}  // namespace re2dj::hle::hardlock

#endif  // RE2DJ_HLE_HARDLOCK_SEED_CONFIG_H_
